# Generated by Django 5.2 on 2025-05-19 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GymUs', '0003_alter_client_options_alter_client_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='client',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='username',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
